- name: CA-åŠ æ‹¿å¤§
  recognition: (?:^|\s)(?:ğŸ‡¨ğŸ‡¦|åŠ æ‹¿å¤§|CA|Canada)(?:\s|$)
- name: US-ç¾å›½
  recognition: (?:^|\s)(?:ğŸ‡ºğŸ‡¸|ç¾å›½|US|United States)(?:\s|$)
- name: JP-æ—¥æœ¬
  recognition: (?:^|\s)(?:ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP|Japan)(?:\s|$)
- name: GB-è‹±å›½
  recognition: (?:^|\s)(?:ğŸ‡¬ğŸ‡§|è‹±å›½|GB|United Kingdom)(?:\s|$)
- name: DE-å¾·å›½
  recognition: (?:^|\s)(?:ğŸ‡©ğŸ‡ª|å¾·å›½|DE|Germany)(?:\s|$)
- name: FR-æ³•å›½
  recognition: (?:^|\s)(?:ğŸ‡«ğŸ‡·|æ³•å›½|FR|France)(?:\s|$)
- name: CN
  recognition: (?:^|\s)(?:ğŸ‡¨ğŸ‡³|ä¸­å›½|CN|China)(?:\s|$)
- name: IN-å°åº¦
  recognition: (?:^|\s)(?:ğŸ‡®ğŸ‡³|å°åº¦|IN|India)(?:\s|$)
- name: BR-å·´è¥¿
  recognition: (?:^|\s)(?:ğŸ‡§ğŸ‡·|å·´è¥¿|BR|Brazil)(?:\s|$)
- name: IT-æ„å¤§åˆ©
  recognition: (?:^|\s)(?:ğŸ‡®ğŸ‡¹|æ„å¤§åˆ©|IT|Italy)(?:\s|$)
- name: RU-ä¿„ç½—æ–¯
  recognition: (?:^|\s)(?:ğŸ‡·ğŸ‡º|ä¿„ç½—æ–¯|RU|Russia)(?:\s|$)
- name: SA-æ²™ç‰¹é˜¿æ‹‰ä¼¯
  recognition: (?:^|\s)(?:ğŸ‡¸ğŸ‡¦|æ²™ç‰¹é˜¿æ‹‰ä¼¯|SA|Saudi Arabia)(?:\s|$)
- name: TW-å°æ¹¾
  recognition: (?:^|\s)(?:ğŸ‡¹ğŸ‡¼|å°æ¹¾|TW|Taiwan)(?:\s|$)
- name: HK-é¦™æ¸¯
  recognition: (?:^|\s)(?:ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|Hong Kong)(?:\s|$)
- name: PK-å·´åŸºæ–¯å¦
  recognition: (?:^|\s)(?:ğŸ‡µğŸ‡°|å·´åŸºæ–¯å¦|PK|Pakistan)(?:\s|$)
- name: IR-ä¼Šæœ—
  recognition: (?:^|\s)(?:ğŸ‡®ğŸ‡·|ä¼Šæœ—|IR|Iran)(?:\s|$)
- name: SG-æ–°åŠ å¡
  recognition: (?:^|\s)(?:ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|SG|Singapore)(?:\s|$)
- name: NL-è·å…°
  recognition: (?:^|\s)(?:ğŸ‡³ğŸ‡±|è·å…°|NL|Netherlands)(?:\s|$)
- name: KR-éŸ©å›½
  recognition: (?:^|\s)(?:ğŸ‡°ğŸ‡·|éŸ©å›½|KR|Korea)(?:\s|$)
- name: AT-å¥¥åœ°åˆ©
  recognition: (?:^|\s)(?:ğŸ‡¦ğŸ‡¹|å¥¥åœ°åˆ©|AT|Austria)(?:\s|$)
- name: CH-ç‘å£«
  recognition: (?:^|\s)(?:ğŸ‡¨ğŸ‡­|ç‘å£«|CH|Switzerland)(?:\s|$)
- name: BE-æ¯”åˆ©æ—¶
  recognition: (?:^|\s)(?:ğŸ‡§ğŸ‡ª|æ¯”åˆ©æ—¶|BE|Belgium)(?:\s|$)
- name: SC-å¡èˆŒå°”
  recognition: (?:^|\s)(?:ğŸ‡¸ğŸ‡¨|å¡èˆŒå°”|SC|Seychelles)(?:\s|$)
- name: UA-ä¹Œå…‹å…°
  recognition: (?:^|\s)(?:ğŸ‡ºğŸ‡¦|ä¹Œå…‹å…°|UA|Ukraine)(?:\s|$)
- name: PT-è‘¡è„ç‰™
  recognition: (?:^|\s)(?:ğŸ‡µğŸ‡¹|è‘¡è„ç‰™|PT|Portugal)(?:\s|$)
- name: RO-ç½—é©¬å°¼äºš
  recognition: (?:^|\s)(?:ğŸ‡·ğŸ‡´|ç½—é©¬å°¼äºš|RO|Romania)(?:\s|$)
- name: IE-çˆ±å°”å…°
  recognition: (?:^|\s)(?:ğŸ‡®ğŸ‡ª|çˆ±å°”å…°|IE|Ireland)(?:\s|$)